language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  # - "pypy3"
env:
  - DJANGO="Django~=1.7.0"
  - DJANGO="Django~=1.8.0"
  - DJANGO="Django~=1.9.0"
  - DJANGO="Django~=1.10.0"
  - DJANGO="Django~=1.11.0"

install:
  - pip install $DJANGO

script:
  - python runtests.py

matrix:
  exclude:
    - env: DJANGO="Django~=1.7.0"
      python: "3.5"
    - env: DJANGO="Django~=1.7.0"
      python: "3.6"
    - env: DJANGO="Django~=1.10.0"
      python: "pypy3"
    - env: DJANGO="Django~=1.11.0"
      python: "pypy3"
    - env: DJANGO="Django~=1.12.0"
      python: "pypy3"
